### PR TITLE
Capture stderr to temp file and output it in test results

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
- new feature
- BC break: no (only additional output in test results)

### CODE REVIEW

**Comment by MartinMystikJonas** [comment]
Any idea why output tests on my computer works just fine but fails in GitHub actions? Output does not match but it seems it should. I suspect some whitespace difference but cannot find it.

**Comment by MartinMystikJonas** [comment]
I still struggle to find what causes tests to fail only in CI. I identified that it is caused by spaces only lines in actual output on CI that does not happens on by local build. But I have no idea why. I will do some more experimentation to find it.

**Comment by MartinMystikJonas** [comment]
Finall I made it pass. I also fixed one coding standard error.

@dg @milo Could oyu check it out and let me know what do you think?

**Comment by milo** [comment]
Looks great. I'll polish it a little bit and I'll merge it.

**Comment by milo** [comment]
@MartinMystikJonas Are you OK with such modifications? https://github.com/milo/tester/tree/MartinMystikJonas-stderr-file

**Comment by MartinMystikJonas** [comment]
@milo Looks OK

**Comment by MartinMystikJonas** [comment]
@milo Is there anything I should do now to finish this PR?

**Comment by milo** [comment]
Thank you. I've merged it.

**Comment by dg** [comment]
Do you have any idea why the `RunnerOutput\OutputHandlers.phpt` test is not passing on Windows? Difference is in progress line:

actual:

```
PHP 8.2.0beta3 (cgi-fcgi) | …

FFFF...ssss
```

expected:
```
PHP 8.2.0beta3 (cgi-fcgi) | …

F.sF.sFsF.s
```

**Comment by MartinMystikJonas** [comment]
I ajve seen something similar when temp dir was not purged between tests so order of tests prioritized failed ones. Why it happens on windows I do not know.

**Comment by dg** [comment]
Bingo, thanks!

**Pull request closed without merging**
