### PR TITLE
Improve parameter names in type assert method

### PR DESCRIPTION
**Pull request by PunchyRascal**
so that it is clear what is the expected and what is the actual value

### CODE REVIEW

**Comment by Majkl578** [comment]
Could you also add phpDoc for parameters (which is missing now)? :)

**Comment by dg** [comment]
:-1: in the same spirit we can change `count($count, $value)` to `count($expectedCount, $actionValue)` and it seems unnecessary.

**Comment by PunchyRascal** [comment]
Unnecessary in what sense? I honestly had no idea what these parameters meant, until I looked into the code itself. I think that variable names like $value, $data, are in most contexts dangerously generic and folks who don't know the code can find it confusing. It is almost as using $string, $number, $a, $b, $c etc.

I added the phpDoc.

**Comment by PunchyRascal** [comment]
I agree that other similarly affected methods should be refactored, too. I might look into it.

**Comment by Majkl578** [comment]
> it seems unnecessar

As it's something that doesn't affect performance, but improves readability & user experience, I'm :+1: .

**Comment by jkuchar** [comment]
I like it; I'm in.

**Comment by PunchyRascal** [comment]
Maybe this PR will merge on its first birthday then? :-D

**Pull request closed without merging**
