### PR TITLE
V1.x

### PR DESCRIPTION
**Pull request by devansdev**
- bug fix / new feature?   
- BC break? yes/no
- doc PR: nette/docs#???

### CODE REVIEW

**Comment by dg** [comment]
Bot?

**Comment by devansdev** [comment]
no, did I do any thing?

**Comment by dg** [comment]
What is the point of this pull request?

**Comment by devansdev** [comment]
no I did not wanted to do a pull request, this is by mistake. Sorry for
that.

**Comment by dg** [comment]
ok

**Pull request closed without merging**
