### PR TITLE
PHP interpreters refactoring II.

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by dg** [comment]
Of course the question is whether distinct between HHVM, phpdbg and PHP by file name or by `--version`. IMHO file name sufficient, but it can be simply changed back. The point is that now it is done out of `CliTester`.

**Comment by Majkl578** [comment]
> IMHO the file name is sufficient

It is not. HHVM is provided as /usr/bin/php on Debian-based systems through /etc/alternatives.

**Comment by dg** [comment]
Ok, I'll change it

**Comment by milo** [comment]
@dg Thanks for review and refactoring!

**Pull request merged**
