### PR TITLE
Minimal PHP version 7.1

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by milo** [comment]
Would you like to merge it soon or is it waiting for one day later?

**Comment by dg** [comment]
It's great for me that exists Tester 2.0 for PHP 5.6. So there is no need to hurry.

**Comment by dg** [comment]
BTW I was surprised that there were so few things that needed to be adjusted to strict types could work https://github.com/nette/tester/pull/384/commits/f645bc259741bc03a70e0cd19312348e5156ff6e

**Comment by dg** [comment]
@milo now it is ready to merge

**Comment by milo** [comment]
Thank you! I'll rebase #378 and ping guys for test it.

**Pull request merged**
