### PR TITLE
Allow manually save partial code coverage to free memory

### PR DESCRIPTION
**Pull request by JanTvrdik**
phpdbg code coverage is very fast but it also consumes a lot of memory because it stores information about every opcode (PHP low-level instruction) executed. This can be alleviated by allowing programmer to manually save partial code coverage to file.

### CODE REVIEW

**Comment by JanTvrdik** [comment]
BTW: Can anyone think of a reason why the file is open in `a+` mode instead of `c+`?

**Comment by dg** [comment]
Because c+ did not exist in PHP 5.2.0

**Comment by JanTvrdik** [comment]
https://github.com/nette/tester/pull/299 is required for new tests for this

**Comment by JanTvrdik** [comment]
rebased

**Comment by JanTvrdik** [comment]
ping

**Comment by milo** [comment]
Thank you.

**Pull request merged**
