### PR TITLE
added Assert::noError

### PR DESCRIPTION
**Pull request by richard-ejem**
…a piece of code does not fail with error or exception

### CODE REVIEW

**Comment by milo** [comment]
Try your solution with:
```php
function aaa()
{
	try {
		bbb();
	} catch (\RuntimeException $e) {
		throw new \RuntimeException('Backend failed', 0, $e);
	}
}

function bbb()
{
	throw new \RuntimeException('This is wrong');
}

Assert::noError(function () {
	aaa();
});
```

You get:
```
Failed: RuntimeException was thrown. Code: 0 Message: Backend failed

in tests\Framework\Assert.noError.phpt(46) Tester\Assert::noError()
```

I'm trying to say, that stack trace and well formatted exceptions chain is crucial here. Imho #251 is good enough.

**Comment by richard-ejem** [comment]
Well, I can add support for printing out stack trace, or maybe even semantically better - list of exception tested not to be thrown. i.e. Assert::noError(function() { new X(new Foo)); }, 'Nette\InvalidArgumentException', "X should accept Foo"); - testing if X constructor accepts Foo. if InvalidArgumentException is thrown, shows user-friendly error message. If something other fails, shows stack trace (the assertion just throws the exception out).

If we decide for your super simple solution, I suggest even simpler:

    public static function noError($function) {
        self::$counter++;
        $function();
    }

as calling to self::error($fn, []) doesn't seem anyhow helpful to me.

**Comment by milo** [comment]
The `noError()` assertion cannot have any argument. It asserts that there will be no error. It even cannot have expectation message, you don't know where error comes from.

The `self::error($fn, [])` solution dumps diff into `output` folder with all errors.

> doesn't seem anyhow helpful to me

And what is? I thought that you want to stop use `Assert::true(TRUE)`?

**Comment by richard-ejem** [comment]
I want to quickly see what failed from the tester output and do it in semantically clear and straightforward way.

> you don't know where error comes from

I kindof do. As written in my example before, i.e. I test that a method accepts certain argument, therefore I explicitly test that the metod does not throw InvalidArgumentException.
If it does, I want to just see "should accept SomeTypeOfArgument". If it throws anything other, yes, stack trace is then useful.

**Comment by milo** [comment]
Closed in favour of e9e1cd82d879574bfc93ad19c6bac53124a0f478.

**Pull request closed without merging**
