### PR TITLE
Support for PHPDBG

### PR DESCRIPTION
**Pull request by milo**
This is my idea how to add support for PHPDBG interpreter for now.

The whole interpreter's interface would deserve refactoring, but it will be with a big BC break.

### CODE REVIEW

**Comment by milo** [comment]
Ref krakjoe/phpdbg#149

**Comment by Mikulas** [comment]
This does not support phpdbg code coverage though, does it? That was kind of the whole point of the original patch, mostly because phpdbg cov is at least twice as fast as xdebug's.

**Comment by JanTvrdik** [comment]
This is useless by itself.

**Comment by milo** [comment]
This PR is reaction to my [comment](https://github.com/nette/tester/pull/258#issuecomment-145285584), it is not your PR replacement.

**Comment by Majkl578** [comment]
This looks like a dirty hack, phpdbg SAPI is completely different from normal CLI (e.g. command line arguments).
Coverage was the only reason why phpdbg was actually needed, because it is much faster. (Btw on my project, xdebug needs 90 seconds to complete, phpdbg needs only 14 seconds, both with PHP 7.0.2 and PHPUnit 5.)

**Comment by milo** [comment]
@Majkl578 

> Coverage was the only reason why phpdbg was actually needed

Yes. And I agree that CC is faster. So what's the problem?

I didn't like the `ZendPhpDbgInterpreter` by @JanTvrdik. Imho, too much code is duplicated. Seems to me that this is more proper way for now. And as I wrote in this PR text, Interpreters would deserve refactoring.

My idea was: merge this and focus only on CC in #258.

**Comment by milo** [comment]
Idea changed :)

**Pull request closed without merging**
