### PR TITLE
Added `console-lines` output mode which prints each test on a separate line

### PR DESCRIPTION
**Pull request by smuuf**
Usage example:
```sh
$ ./src/tester -C -o console-lines tests/
```

This is handy for environments with "non-standard" _(buffered, I guess?)_ handling of standard output, for example `Github Actions` _(where a progress of tests cannot be seen until until end-of-line appears, which in standard `console` mode happens only when all tests finish)_ or `Docker Compose` logging output _(where in standard `console` mode each finished test's dot is printed alone on separate line)_.

Or the `console-lines` mode can be handy just to see a more detailed progress of tests in all environments, because it outputs something like this:

<table>
<tr>
<td>Passing tests</td>
<td>Failing tests</td>
<td>Usage</td>
<td>Also supports "cider mode"</td>
<tr/>
<tr>
<td>

obrazek

</td>
<td>

obrazek

</td>
<td>

obrazek

</td>
<td>

obrazek

</td>
<tr/>
</table>

Also, "cider mode" now shows a lemon emoji for skipped tests.

- ***new feature***
- BC break? ***no***
- doc PR: https://github.com/nette/docs/pull/1027

### CODE REVIEW

**Comment by dg** [comment]
I like that! I'd probably just use a slightly different name, like `-o verbose`?

**Comment by smuuf** [comment]
I'd think `verbose` could mean different things for different output modes, so maybe usurping the word `verbose` for something related just to the `console` output might not be the best thing to do, future-wise, but other than that I have no strong opinion on that 😄

If you'd prefer `verbose`, I can make it be called `verbose`.

**Comment by smuuf** [comment]
Updated: Renamed to `verbose` + updated the relevant [PR to docs](https://github.com/nette/docs/pull/1027).

**Comment by dg** [comment]
I was just throwing that out there, I'm sure someone can think of something better.

**Comment by MartinMystikJonas** [comment]
Imho 'console-lines' was better. Or just 'lines'?

**Pull request merged**
