### PR TITLE
TestCaseListener for listening on TestCase events

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
Alternative solution #246 for RFC #245.

See https://forum.nette.org/en/24028-rfc-testcase-events-for-tester#p161184

### CODE REVIEW

**Comment by milo** [comment]
Thank you for the PR. But imho this is error prone to method name typo.

What is disadvantage of following?
```php
class TestCase
{
    public function onEvent(string $eventName, callable $cb) {}
}

**Comment by MartinMystikJonas** [comment]
What do you mean by error prone to method name typo? All methods are defined in interfaces.

**Comment by milo** [comment]
@MartinMystikJonas Oh, I'm sorry. I mixed up in my head with other things.

**Comment by MartinMystikJonas** [comment]
@milo Shit happens :-) So what is your opinion on this solution?

**Comment by jkuchar** [comment]
Are there any news on this?

**Comment by milo** [comment]
@jkuchar Not from my side :( Didn't find a time to play with it.

**Comment by JanTvrdik** [comment]
I still thinks it is a bad idea.

**Comment by MartinMystikJonas** [comment]
@JanTvrdik Why is it bad idea?

**Pull request closed without merging**
