### PR TITLE
Runner: run *.phpt and *Test.php as default

### PR DESCRIPTION
**Pull request by milo**
- bug fix? no
- new feature? yes #278
- BC break? yes
- doc PR: (will)

Not sure for what was the `Runner::TEST_FILE_EXTENSION` good for.

### CODE REVIEW

**Comment by klapuch** [comment]
@milo What if my test folder includes PHPUnit tests (because of snapshot testing) and Nette Tester tests? Nowadays, I have to list all my folders with Nette Tester tests and pass them to CLI command. In the old version I just passed `Tests/` folder and I was fine. Can I somehow force the old rule with `*.phpt`?

Thanks

**Comment by JanTvrdik** [comment]
> I have to list all my folders with Nette Tester tests and pass them to CLI command

That seems like something you should have always be doing.

**Comment by milo** [comment]
@klapuch You can reorganize your test files, e.g.
```
tests\
    Tester\
    PHPUnit\
```
Or, if your shell supports it, use `**` wild card, e.g. `vendor/bin/tester  tests/**/*.phpt`.

**Comment by klapuch** [comment]
@JanTvrdik Why? Using Nette Tester to recursively execute all my tests in `Tests/` folder was always fine for me and I had no problems. When I create brand new folder for my tests (in `Tests/`), I have to put it to `build.xml`. It is very easy to forget it.

**Comment by klapuch** [comment]
@milo Yeah, I though about the structure too, but honestly, I would like to keep my tests independently on framework. Does the `**` wildcard is supported by default when I run tester via `vendor/bin/tester`?

**Comment by milo** [comment]
Function of `**` depends on your shell, not on the Tester.

**Pull request merged**
